### ISSUE TITLE
`emf2svg` not installing the published platform gem built for `arm64-linux`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/emf2svg-ruby#18]
https://rubygems.org/gems/emf2svg/versions
<img width="681" alt="Screenshot 2022-03-22 at 10 32 33 PM" src="https://user-images.githubusercontent.com/11865/159506090-dacf8a70-7db8-4664-9d61-cb557d62673b.png">

Apparently the gem is published, but not installed on this platform?

Related to #15 

```sh
docker run --platform=linux/arm64/v8 -it ruby:3.1-alpine sh
/ # apk add gcc g++ cmake make libc-dev
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
(1/25) Installing libacl (2.2.53-r0)
(2/25) Installing libbz2 (1.0.8-r1)
(3/25) Installing expat (2.4.7-r0)
(4/25) Installing lz4-libs (1.9.3-r1)
(5/25) Installing xz-libs (5.2.5-r0)
(6/25) Installing zstd-libs (1.5.0-r0)
(7/25) Installing libarchive (3.6.0-r0)
(8/25) Installing brotli-libs (1.0.9-r5)
(9/25) Installing nghttp2-libs (1.46.0-r0)
(10/25) Installing libcurl (7.80.0-r0)
(11/25) Installing rhash-libs (1.4.2-r2)
(12/25) Installing libuv (1.42.0-r0)
(13/25) Installing cmake (3.21.3-r0)
(14/25) Installing binutils (2.37-r3)
(15/25) Installing libgomp (10.3.1_git20211027-r0)
(16/25) Installing libatomic (10.3.1_git20211027-r0)
(17/25) Installing libgphobos (10.3.1_git20211027-r0)
(18/25) Installing isl22 (0.22-r0)
(19/25) Installing mpfr4 (4.1.0-r0)
(20/25) Installing mpc1 (1.2.1-r0)
(21/25) Installing gcc (10.3.1_git20211027-r0)
(22/25) Installing musl-dev (1.2.2-r7)
(23/25) Installing libc-dev (0.7.2-r3)
(24/25) Installing g++ (10.3.1_git20211027-r0)
(25/25) Installing make (4.3-r0)
Executing busybox-1.34.1-r4.trigger
OK: 250 MiB in 60 packages
/ # gem install emf2svg
Fetching emf2svg-1.2.0.gem
Fetching mini_portile2-2.8.0.gem
Fetching ffi-1.15.5.gem
Successfully installed mini_portile2-2.8.0
Building native extensions. This could take a while...
Successfully installed ffi-1.15.5
Building native extensions. This could take a while...
ERROR:  Error installing emf2svg:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/emf2svg-1.2.0/ext
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r ./siteconf20220322-11-ghyg5o.rb extconf.rb
Downloading libemf2svg.tar.gz (  0%) 
Extracting libemf2svg.tar.gz into /tmp/d20220322-172-9tl39l... DEBUG: env is {}
DEBUG: command is ["tar", "zxf", "/usr/local/bundle/gems/emf2svg-1.2.0/ports/archives/libemf2svg.tar.gz", "-C", "/tmp/d20220322-172-9tl39l"]
DEBUG: options are {[:out, :err]=>["/tmp/d20220322-172-9tl39l/extract.log", "a"]}
OK
/usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:52:in `host_platform': CrossRuby.platform: unsupported host: aarch64-alpine-linux-musl (RuntimeError)
	from /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:63:in `cross_compiling?'
	from /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:75:in `configure_defaults'
	from /usr/local/bundle/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:125:in `configure_options'
	from /usr/local/bundle/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:272:in `computed_options'
	from /usr/local/bundle/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile_cmake.rb:38:in `configured?'
	from /usr/local/bundle/gems/mini_portile2-2.8.0/lib/mini_portile2/mini_portile.rb:186:in `cook'
	from /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:27:in `cook'
	from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/bundle/gems/emf2svg-1.2.0 for inspection.
Results logged to /usr/local/bundle/extensions/aarch64-linux-musl/3.1.0/emf2svg-1.2.0/gem_make.out
/ # 
```

This is the cause of failure in https://github.com/metanorma/metanorma-docker/runs/5644436127?check_suite_focus=true:

```
2022-03-22T14:24:18.5485704Z #14 3901.6 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
2022-03-22T14:24:18.5486458Z #14 3901.6 
2022-03-22T14:24:18.5487210Z #14 3901.6     current directory: /usr/local/bundle/gems/emf2svg-1.2.0/ext
2022-03-22T14:24:18.5487819Z #14 3901.6 /usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r
2022-03-22T14:24:18.5488776Z #14 3901.6 ./siteconf20220322-9-j9ysfr.rb extconf.rb
2022-03-22T14:24:18.5490325Z #14 3901.6 
2022-03-22T14:24:18.5490584Z Downloading libemf2svg.tar.gz (  0%) 
2022-03-22T14:24:18.5491102Z #14 3901.6 Extracting libemf2svg.tar.gz into /tmp/d20220322-13305-l7dxr4... DEBUG: env is
2022-03-22T14:24:18.5491413Z #14 3901.6 {}
2022-03-22T14:24:18.5491658Z #14 3901.6 DEBUG: command is ["tar", "zxf",
2022-03-22T14:24:18.5492100Z #14 3901.6 "/usr/local/bundle/gems/emf2svg-1.2.0/ports/archives/libemf2svg.tar.gz", "-C",
2022-03-22T14:24:18.5492674Z #14 3901.6 "/tmp/d20220322-13305-l7dxr4"]
2022-03-22T14:24:18.5493244Z #14 3901.6 DEBUG: options are {[:out, :err]=>["/tmp/d20220322-13305-l7dxr4/extract.log",
2022-03-22T14:24:18.5493631Z #14 3901.6 "a"]}
2022-03-22T14:24:18.5493865Z #14 3901.6 OK
2022-03-22T14:24:18.5494333Z #14 3901.6 /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:52:in
2022-03-22T14:24:18.5494959Z #14 3901.6 `host_platform': CrossRuby.platform: unsupported host: aarch64-linux-gnu
2022-03-22T14:24:18.5495372Z #14 3901.6 (RuntimeError)
2022-03-22T14:24:18.5495799Z #14 3901.6 from /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:63:in
2022-03-22T14:24:18.5496191Z #14 3901.6 `cross_compiling?'
2022-03-22T14:24:18.5496627Z #14 3901.6 from /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:75:in
2022-03-22T14:24:18.5497015Z #14 3901.6 `configure_defaults'
2022-03-22T14:24:18.5497330Z #14 3901.6 from
2022-03-22T14:24:18.5497788Z #14 3901.6 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:118:in
2022-03-22T14:24:18.5498204Z #14 3901.6 `configure_options'
2022-03-22T14:24:18.5498508Z #14 3901.6 from
2022-03-22T14:24:18.5499127Z #14 3901.6 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:257:in
2022-03-22T14:24:18.5499569Z #14 3901.6 `computed_options'
2022-03-22T14:24:18.5499860Z #14 3901.6 from
2022-03-22T14:24:18.5500311Z #14 3901.6 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile_cmake.rb:33:in
2022-03-22T14:24:18.5500723Z #14 3901.6 `configured?'
2022-03-22T14:24:18.5500962Z #14 3901.6 from
2022-03-22T14:24:18.5501464Z #14 3901.6 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:179:in
2022-03-22T14:24:18.5501851Z #14 3901.6 `cook'
2022-03-22T14:24:18.5502283Z #14 3901.6 	from /usr/local/bundle/gems/emf2svg-1.2.0/lib/emf2svg/recipe.rb:27:in `cook'
2022-03-22T14:24:18.5502695Z #14 3901.6 	from extconf.rb:6:in `<main>'
2022-03-22T14:24:18.5502950Z #14 3901.6 
2022-03-22T14:24:18.5503184Z #14 3901.6 extconf failed, exit code 1
2022-03-22T14:24:18.5503418Z #14 3901.6 
2022-03-22T14:24:18.5504367Z #14 3901.6 Gem files will remain installed in /usr/local/bundle/gems/emf2svg-1.2.0 for
2022-03-22T14:24:18.5504787Z #14 3901.6 inspection.
2022-03-22T14:24:18.5505231Z #14 3901.6 Results logged to
2022-03-22T14:24:18.5505740Z #14 3901.6 /usr/local/bundle/extensions/aarch64-linux/3.1.0/emf2svg-1.2.0/gem_make.out
2022-03-22T14:24:18.5506106Z #14 3901.6 
2022-03-22T14:24:18.5506404Z #14 3901.6   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
2022-03-22T14:24:18.5506858Z #14 3901.6 /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
2022-03-22T14:24:18.5507232Z #14 3901.6 build'
2022-03-22T14:24:18.5507579Z #14 3901.6   /usr/local/lib/ruby/3.1.0/tempfile.rb:317:in `open'
2022-03-22T14:24:18.5508009Z #14 3901.6   /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
2022-03-22T14:24:18.5508471Z #14 3901.6   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
2022-03-22T14:24:18.5508920Z #14 3901.6 /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
2022-03-22T14:24:18.5509304Z #14 3901.6 build_extensions'
2022-03-22T14:24:18.5509686Z #14 3901.6   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
2022-03-22T14:24:18.5510137Z #14 3901.6   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
2022-03-22T14:24:18.5510599Z #14 3901.6   /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
2022-03-22T14:24:18.5511190Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:71:in
2022-03-22T14:24:18.5511600Z #14 3901.6 `build_extensions'
2022-03-22T14:24:18.5512119Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/rubygems_gem_installer.rb:28:in
2022-03-22T14:24:18.5512506Z #14 3901.6 `install'
2022-03-22T14:24:18.5512929Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/source/rubygems.rb:204:in
2022-03-22T14:24:18.5513240Z #14 3901.6 `install'
2022-03-22T14:24:18.5513688Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:54:in
2022-03-22T14:24:18.5514009Z #14 3901.6 `install'
2022-03-22T14:24:18.5514428Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/gem_installer.rb:16:in
2022-03-22T14:24:18.5514755Z #14 3901.6 `install_from_spec'
2022-03-22T14:24:18.5515280Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:186:in
2022-03-22T14:24:18.5515706Z #14 3901.6 `do_install'
2022-03-22T14:24:18.5516223Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer/parallel_installer.rb:177:in
2022-03-22T14:24:18.5516648Z #14 3901.6 `block in worker_pool'
2022-03-22T14:24:18.5517113Z #14 3901.6   /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:62:in `apply_func'
2022-03-22T14:24:18.5517695Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:57:in `block in
2022-03-22T14:24:18.5518088Z #14 3901.6 process_queue'
2022-03-22T14:24:18.5518589Z #14 3901.6   /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in `loop'
2022-03-22T14:24:18.5519151Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:54:in
2022-03-22T14:24:18.5519524Z #14 3901.6 `process_queue'
2022-03-22T14:24:18.5520014Z #14 3901.6 /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/worker.rb:91:in `block (2
2022-03-22T14:24:18.5520417Z #14 3901.6 levels) in create_threads'
2022-03-22T14:24:18.5520724Z #14 3901.6 
2022-03-22T14:24:18.5521046Z #14 3901.6 An error occurred while installing emf2svg (1.2.0), and Bundler cannot continue.
2022-03-22T14:24:18.5521445Z #14 3901.6 
2022-03-22T14:24:18.5521672Z #14 3901.6 In Gemfile:
2022-03-22T14:24:18.5522135Z #14 3901.6   metanorma-cli was resolved to 1.5.12pre, which depends on
2022-03-22T14:24:18.5522664Z #14 3901.6     metanorma-bipm was resolved to 2.0.5, which depends on
2022-03-22T14:24:18.5523202Z #14 3901.6       metanorma-generic was resolved to 2.0.4, which depends on
2022-03-22T14:24:18.5523751Z #14 3901.6         metanorma-standoc was resolved to 2.0.5.3, which depends on
2022-03-22T14:24:18.5524528Z #14 3901.6           metanorma-plugin-datastruct was resolved to 0.2.0, which depends on
2022-03-22T14:24:18.5525001Z #14 3901.6             isodoc was resolved to 2.0.6.1, which depends on
2022-03-22T14:24:18.5525366Z #14 3901.6               emf2svg
```

**Comment by maxirmx** [comment]
This image describes itself as `aarch64-linux` while extension is tagged as `arm64-linux`
I will need some time to have it cleared
