### ISSUE TITLE
Docker ignore prebuilt gem

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/emf2svg-ruby#21]
For some reason, docker still ignores prebuilt emf2svg 1.3.0

I just checked .so file with `file` and it looks right: 

```
➜  file ~/Documents/emf2svg-1.3.0-arm64-linux/data/lib/emf2svg/libemf2svg.so
~/Documents/emf2svg-1.3.0-arm64-linux/data/lib/emf2svg/libemf2svg.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, BuildID[sha1]=dd92c53c16b1570ee426673932e67b436d144933, not stripped
```

<details>
  <summary>More details, docker aarch64 build log</summary>

  ```
  #15 2978.1 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
  #15 2978.1 
  #15 2978.1     current directory: /usr/local/bundle/gems/emf2svg-1.3.0/ext
  #15 2978.1 /usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r
  #15 2978.1 ./siteconf20220402-7-oc6n3x.rb extconf.rb
  #15 2978.1 
  Downloading libemf2svg.tar.gz (  0%) 
  #15 2978.1 Extracting libemf2svg.tar.gz into /tmp/d20220402-13137-fymzky... DEBUG: env is
  #15 2978.1 {}
  #15 2978.1 DEBUG: command is ["tar", "zxf",
  #15 2978.1 "/usr/local/bundle/gems/emf2svg-1.3.0/ports/archives/libemf2svg.tar.gz", "-C",
  #15 2978.1 "/tmp/d20220402-13137-fymzky"]
  #15 2978.1 DEBUG: options are {[:out, :err]=>["/tmp/d20220402-13137-fymzky/extract.log",
  #15 2978.1 "a"]}
  #15 2978.1 OK
  #15 2978.1 DEBUG: env is {}
  #15 2978.1 DEBUG: command is ["cmake", "-DCMAKE_BUILD_TYPE=Release",
  #15 2978.1 "-DCMAKE_INSTALL_PREFIX=/usr/local/bundle/gems/emf2svg-1.3.0/ext/port", "."]
  #15 2978.1 Running 'configure' for libemf2svg 1.6.0... DEBUG: options are {[:out,
  #15 2978.1 :err]=>["/tmp/d20220402-13137-fymzky/configure.log", "a"]}
  #15 2978.1 ERROR, review '/tmp/d20220402-13137-fymzky/configure.log' to see what happened.
  #15 2978.1 Last lines are:
  #15 2978.1 ========================================================================
  #15 2978.1 -- Detecting C compiler ABI info - done
  #15 2978.1 -- Check for working C compiler: /usr/bin/cc - skipped
  #15 2978.1 -- Detecting C compile features
  #15 2978.1 -- Detecting C compile features - done
  #15 2978.1 -- Detecting CXX compiler ABI info
  #15 2978.1 -- Detecting CXX compiler ABI info - done
  #15 2978.1 -- Check for working CXX compiler: /usr/bin/c++ - skipped
  #15 2978.1 -- Detecting CXX compile features
  #15 2978.1 -- Detecting CXX compile features - done
  #15 2978.1 -- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.11") 
  #15 2978.1 CMake Error at
  #15 2978.1 /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  #15 2978.1   Could NOT find PNG (missing: PNG_LIBRARY PNG_PNG_INCLUDE_DIR)
  #15 2978.1 Call Stack (most recent call first):
  #15 2978.1 /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458
  #15 2978.1 (_FPHSA_FAILURE_MESSAGE)
  #15 2978.1 /usr/share/cmake-3.18/Modules/FindPNG.cmake:156
  #15 2978.1 (find_package_handle_standard_args)
  #15 2978.1   CMakeLists.txt:35 (find_package)
  #15 2978.1 
  #15 2978.1 
  #15 2978.1 -- Configuring incomplete, errors occurred!
  #15 2978.1 See also "/tmp/d20220402-13137-fymzky/libemf2svg/CMakeFiles/CMakeOutput.log".
  #15 2978.1 ========================================================================
  #15 2978.1 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:443:in
  #15 2978.1 `block in execute': Failed to complete configure task (RuntimeError)
  #15 2978.1 from
  #15 2978.1 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in
  #15 2978.1 `chdir'
  #15 2978.1 from
  #15 2978.1 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:409:in
  #15 2978.1 `execute'
  #15 2978.1 from /usr/local/bundle/gems/emf2svg-1.3.0/lib/emf2svg/recipe.rb:130:in
  #15 2978.1 `execute'
  #15 2978.1 from
  #15 2978.1 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile_cmake.rb:24:in
  #15 2978.1 `configure'
  #15 2978.1 from
  #15 2978.1 /usr/local/bundle/gems/mini_portile2-2.6.1/lib/mini_portile2/mini_portile.rb:179:in
  #15 2978.1 `cook'
  #15 2978.1  from /usr/local/bundle/gems/emf2svg-1.3.0/lib/emf2svg/recipe.rb:27:in `cook'
  #15 2978.1  from extconf.rb:6:in `<main>'
  #15 2978.1 
  #15 2978.1 extconf failed, exit code 1
  #15 2978.1 
  #15 2978.1 Gem files will remain installed in /usr/local/bundle/gems/emf2svg-1.3.0 for
  #15 2978.1 inspection.
  #15 2978.1 Results logged to
  #15 2978.1 /usr/local/bundle/extensions/aarch64-linux/3.1.0/emf2svg-1.3.0/gem_make.out
  #15 2978.1 
  #15 2978.1   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:95:in `run'
  #15 2978.1 /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:47:in `block in
  #15 2978.1 build'
  #15 2978.1   /usr/local/lib/ruby/3.1.0/tempfile.rb:317:in `open'
  #15 2978.1   /usr/local/lib/ruby/3.1.0/rubygems/ext/ext_conf_builder.rb:26:in `build'
  #15 2978.1   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:161:in `build_extension'
  #15 2978.1 /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:195:in `block in
  #15 2978.1 build_extensions'
  #15 2978.1   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `each'
  #15 2978.1   /usr/local/lib/ruby/3.1.0/rubygems/ext/builder.rb:192:in `build_extensions'
  #15 2978.1   /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:853:in `build_extensions'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/rubygems_gem_installer.rb:71:in
  #15 2978.1 `build_extensions'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/rubygems_gem_installer.rb:28:in
  #15 2978.1 `install'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/source/rubygems.rb:204:in
  #15 2978.1 `install'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/installer/gem_installer.rb:54:in
  #15 2978.1 `install'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/installer/gem_installer.rb:16:in
  #15 2978.1 `install_from_spec'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/installer/parallel_installer.rb:186:in
  #15 2978.1 `do_install'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/installer/parallel_installer.rb:177:in
  #15 2978.1 `block in worker_pool'
  #15 2978.1   /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/worker.rb:62:in `apply_func'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/worker.rb:57:in `block in
  #15 2978.1 process_queue'
  #15 2978.1   /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/worker.rb:54:in `loop'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/worker.rb:54:in
  #15 2978.1 `process_queue'
  #15 2978.1 /usr/local/bundle/gems/bundler-2.3.10/lib/bundler/worker.rb:91:in `block (2
  #15 2978.1 levels) in create_threads'
  #15 2978.1 
  #15 2978.1 An error occurred while installing emf2svg (1.3.0), and Bundler cannot continue.
  #15 2978.1 
  #15 2978.1 In Gemfile:
  #15 2978.1   metanorma-cli was resolved to 1.5.12, which depends on
  #15 2978.1     metanorma-bipm was resolved to 2.0.6, which depends on
  #15 2978.1       metanorma-generic was resolved to 2.0.4, which depends on
  #15 2978.1         metanorma-standoc was resolved to 2.0.5.3, which depends on
  #15 2978.1           metanorma-plugin-datastruct was resolved to 0.2.0, which depends on
  #15 2978.1             isodoc was resolved to 2.0.6.1, which depends on
  #15 2978.1               emf2svg

  ```

</details>

Full log https://github.com/metanorma/metanorma-docker/runs/5760850636?check_suite_focus=true

@maxirmx maybe you have some idea

**Comment by CAMOBAP** [comment]
UPD. I have an assumption that this is because of wrong triplet name `arm64-linux` should be replaced with `aarch64-linux`

**Comment by maxirmx** [comment]
It first missed platform and then failed to build the extension
The second problem occured because vcpkg is called to install dependencies only if we cross-compile.  Probably this needs to be fixed as well.

**Comment by CAMOBAP** [comment]
> It first missed platform and then failed to build the extension

This one should be fixed by #22, release on the way https://github.com/metanorma/emf2svg-ruby/actions/runs/2084749795

> The second problem occured because vcpkg is called to install dependencies only if we cross-compile. Probably this needs to be fixed as well.

@maxirmx  I agree, ideally, this should be fixed also, but as far as I understand this not done yet due to some issues, right?

**Comment by CAMOBAP** [comment]
I can confirm that fix for prebuilt works (tested on metanorma-docker-private)

**Comment by ronaldtse** [comment]
Thanks! Please help close this if it's fixed.

**Comment by CAMOBAP** [comment]
@ronaldtse actually I agree with @maxirmx that it will be extremely helpful to make vcpgk work (probably we need to check if it is available and if so use it for dependencies)

Here is runs after fix:
 - https://github.com/metanorma/metanorma-docker-private/runs/5808506625?check_suite_focus=true - all arm64 passed
 - https://github.com/metanorma/metanorma-docker/actions/runs/2066558041 (still in progress)

@maxirmx is that of if I will assign the ticket for you for to continue work on vcpkg (or I can create a new one, up to you)?

**Comment by ronaldtse** [comment]
Got it. Probably a new ticket is more appropriate.

**Comment by maxirmx** [comment]
https://github.com/metanorma/emf2svg-ruby/issues/23#issuecomment-1087272208

**Comment by ronaldtse** [comment]
Closing since vcpkg is now in #23. Thanks!
