### ISSUE TITLE
`gem install emf2svg` is installing the wrong platform precompiled version

### ISSUE THREAD

**Issue by opoudjis** [metanorma/emf2svg-ruby#28]
````
bundler: failed to load command: asciidoctor (/Users/nickn/.rbenv/versions/3.1.1/bin/asciidoctor)
/Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib': dlopen(/Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib, 0x0005): tried: '/Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) (LoadError)
	from /Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
	from /Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `ffi_lib'
	from /Users/nickn/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg.rb:28:in `<module:Emf2svg>'
````

No idea why this is getting confused between arm64 and x64_64, but it needs not to be. Will disable emf2svg 1.4 until this is resolved.

**Comment by ronaldtse** [comment]
FYI @opoudjis is on M1.

I can verify that this is the same on mine (M1).

```sh
$ gem install emf2svg
Successfully installed emf2svg-1.4.0-arm64-darwin
1 gem installed
$ irb
irb(main):001:0> require 'emf2svg'
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library '/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib': dlopen(/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib, 0x0005): tried: '/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) (LoadError)
        from /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi/library.rb:99:in `map'
```

It's installing the x86_64 version for arm64.

**Comment by ronaldtse** [comment]
This is what `file` tells me:

```sh
$ file /Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib
/Users/me/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/emf2svg-1.4.0-arm64-darwin/lib/emf2svg/libemf2svg.dylib: Mach-O 64-bit dynamically linked shared library x86_64
```

**Comment by ronaldtse** [comment]
Is it possible to create a "universal binary" for macOS, e.g.
https://www.indiehackers.com/product/softmeter-application-analytics/building-a-macos-universal-binary-arm64-x86-64--MMXBITKA6c7x4Efmalv
?

**Comment by maxirmx** [comment]
https://github.com/microsoft/vcpkg/issues/22498

**Comment by maxirmx** [comment]
> Is it possible to create a "universal binary" for macOS, e.g.
> https://www.indiehackers.com/product/softmeter-application-analytics/building-a-macos-universal-binary-arm64-x86-64--MMXBITKA6c7x4Efmalv
> ?

It is possible to create a "universal binary" for MacOS but it seems that bundler is looking for the file targeting specific architecture. So such universal binary won't be useful as a native extension

**Comment by maxirmx** [comment]
@ronaldtse @opoudjis 
It shall have correct binary at [1.4.1 ](https://rubygems.org/gems/emf2svg/versions/1.4.1)
I am sorry for the mess

**Comment by ronaldtse** [comment]
@maxirmx I can confirm that 1.4.1 works. Thanks!
